export const ROUTES = {
  MAIN: '/',
  SIGN_IN: '/oauth',
  SIGN_UP: '/sign-up',
  PROFILE: '/profile',
  GAME: '/game',
  LEADERBOARD: '/leaderboard',
  START_GAME: '/start-game',
  END_GAME: '/end-game',
  FORUM: '/forum',
  FORUM_MESSAGE: '/forum/:id',
  NOT_FOUND: '/not-found',
  SERVER_ERROR: '/500',
  TEST_CORE: '/test-core',
  FORUM_NEW: '/forum/new',
} as const
