name: Lint

on:
  pull_request:
  push:
    branches:
      - main
      - dev

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: corepack enable
        run: corepack enable
      - name: corepack prepare
        run: corepack prepare yarn@4.6.0 --activate
      - name: Install main deps
        run: yarn
      - name: Initialize
        run: yarn lerna bootstrap
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
